services:
    auth:
        build:
            context: .
            dockerfile: cmd/auth/Dockerfile
        ports:
            - '8080:8080'
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=admin
            - DB_PASSWORD=123a@
            - DB_NAME=learning_platform
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:17-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=123a@
            - POSTGRES_DB=learning_platform
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U admin -d learning_platform']
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
